version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: sport-events-bot-api
    restart: always
    environment:
      - BOTMASTER_PORT=3000
      - MONGODB_HOST=sport-events-bot-mongo-database
      - MONGODB_PORT=27017
      - MONGODB_DB=sportevents
      - WS_URL=https://www.ole.com.ar/wg-agenda-deportiva/json/agenda.json
      - FUTBOL_NAME=Fútbol
      - TELEGRAM_BOT_TOKEN=
      - TELEGRAM_BOT_WEBHOOK_PATH=webhookToChange
      - EXTERNAL_URL=http://localhost:3000/
    depends_on:
      - mongo-database
    networks:
      - sport-events-bot-api
  mongo-database:
    image: mongo:4
    restart: always
    container_name: sport-events-bot-mongo-database
    networks:
      - sport-events-bot-api
networks:
  sport-events-bot-api:
